name: "Build"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST_REDIS_URI: "redis://localhost:6379"
      TEST_REDIS5_URI: "redis://localhost:6383"
      TEST_REDIS6_URI: "redis://localhost:6379"
      TEST_REDIS7_URI: "redis://localhost:6384"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...


    services:
      redis5:
        image: redis:5
        ports:
          - 6383:6379
      redis6:
        image: redis:6.2
        ports:
          - 6379:6379
      redis7:
        image: redis:7.0
        ports:
          - 6384:6379
